spring.application.name=LeaveManagement

# PostgreSQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/leave_management}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Diksha@101}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:ThisIsMyVerySecureSecretKeyForJwtAuthentication12345}
jwt.expiration=${JWT_EXPIRATION:604800000}

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# OpenAPI Docs
springdoc.api-docs.path=/v3/api-docs
